[project]
name = "context"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "numpy>=2.2.0",
    "polars>=1.17.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
